# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mgccli < Formula
  desc ""
  homepage "https://test.geff.ws/download/cli/latest"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "http://test.geff.ws/download/cli/v0.1.0/mgccli_0.1.0_darwin_amd64.tar.gz"
      sha256 "c5dd1d4da01b9df2bb28aa700c71c85ef501e22ae927783e147e9e5f32060ce7"

      def install
        bin.install "mgccli"
      end
    end
    if Hardware::CPU.arm?
      url "http://test.geff.ws/download/cli/v0.1.0/mgccli_0.1.0_darwin_arm64.tar.gz"
      sha256 "a10d7f279f374d72fca46cccfd642273d925405c7c7dca4627ece15e2309f2a7"

      def install
        bin.install "mgccli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://test.geff.ws/download/cli/v0.1.0/mgccli_0.1.0_linux_arm64.tar.gz"
      sha256 "bd5a35d3a5086cfa65274bcefb02fc42cce77da750f3f85b09409e5a1a0f2f1a"

      def install
        bin.install "mgccli"
      end
    end
    if Hardware::CPU.intel?
      url "http://test.geff.ws/download/cli/v0.1.0/mgccli_0.1.0_linux_amd64.tar.gz"
      sha256 "d75f433f29e716bf360ec503f9e9d3e3883f695fe33d326742f64c2b452763da"

      def install
        bin.install "mgccli"
      end
    end
  end
end
