# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mgccli < Formula
  desc ""
  homepage "https://github.com/geffersonFerraz/test-goreleaser"
  version "0.0.11"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/geffersonFerraz/test-goreleaser/releases/download/v0.0.11/mgccli_0.0.11_darwin_arm64.tar.gz"
      sha256 "c877c6823ad6fd99d3c2b92e2f06ab7990c03f8c6cb795254d9d58a447c31d80"

      def install
        bin.install "mgccli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/geffersonFerraz/test-goreleaser/releases/download/v0.0.11/mgccli_0.0.11_darwin_amd64.tar.gz"
      sha256 "e263d252e4a185d6518c6b4e5ec11c863e9a578bb82b5b4c2d8b8a146d709595"

      def install
        bin.install "mgccli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geffersonFerraz/test-goreleaser/releases/download/v0.0.11/mgccli_0.0.11_linux_arm64.tar.gz"
      sha256 "d1e7640b17412bb25792e7e4d10b1d8ea7c477cbd2b66a05955717b77b06f38b"

      def install
        bin.install "mgccli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/geffersonFerraz/test-goreleaser/releases/download/v0.0.11/mgccli_0.0.11_linux_amd64.tar.gz"
      sha256 "215564eac65c785ed3cc15ca4ba38242804b2798c572d1d3711b9b05cfe572d1"

      def install
        bin.install "mgccli"
      end
    end
  end
end
